info:
    description: "College Student API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "College REST"
    version: "v1.0"
openapi: "3.0.1"
components:
    schemas:
        Student:
            properties:
                studentId:
                    type: integer
                    format: int64
                name:
                    type: string
                branch:
                    type: string
                year:
                    type: integer
                    format: int32
            type: object
paths:
    /students:
        post:
            operationId: postStudent
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Student"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Student"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Student"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Student"
                    description: "Create a student"
            tags: [ "Student" ]
        get:
            operationId: getStudents
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Student"
                                    page:
                                        type: integer
                                    pageSize:
                                        type: integer
                                    totalCount:
                                        type: integer
                                    lastPage:
                                        type: integer
                        application/xml:
                            schema:
                                type: object
                                properties:
                                    items:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Student"
                    description: "Get all students with pagination"
            tags: ["Student"]
    /students/{studentId}:
        get:
            operationId: getStudent
            parameters:
                - in: path
                  name: studentId
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Student"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Student"
                    description: "Get a specific student"
            tags: ["Student"]
        put:
            operationId: putStudent
            parameters:
                - in: path
                  name: studentId
                  required: true
                  schema:
                      type: integer
                      format: int64
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Student"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Student"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Student"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Student"
                    description: "Update a student"
            tags: ["Student"]
        delete:
            operationId: deleteStudent
            parameters:
                - in: path
                  name: studentId
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                204:
                    description: "Student deleted"
            tags: ["Student"]